# Generated by Django 3.1.3 on 2020-12-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('place', models.IntegerField(default=0)),
                ('desciption', models.CharField(default='', max_length=120)),
                ('image', models.ImageField(upload_to='product/')),
            ],
        ),
    ]
